apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-issuers.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: agenthive
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true
    includeTemplates: true
