spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:3001"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders:
              - Content-Type
              - Accept
              - Authorization
              - X-Query-Params
              - X-Requested-With
              - X-User-Id
              - X-User-Name
              - X-User-Role
            allowCredentials: true
            maxAge: 3600
