server:
  port: 8082

spring:
  application:
    name: user-service
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
    openfeign:
      client:
        config:
          auth-service:
            url: http://auth-service:8081
