server:
  port: 8082

spring:
  application:
    name: user-service
  data:
    redis:
      host: redis
      port: 6379
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
    openfeign:
      client:
        config:
          auth-service:
            url: http://auth-service:8081
