server:
  port: 8083

spring:
  application:
    name: payment-service
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  cloud:
    nacos:
      config:
        import-check:
          enabled: false

order-service:
  url: http://order-service:8084
