server:
  port: 8083

spring:
  application:
    name: payment-service
  data:
    redis:
      host: redis
      port: 6379
  cloud:
    nacos:
      config:
        import-check:
          enabled: false

order-service:
  url: http://order-service:8084
