apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: agenthive
spec:
  replicas: 1
  template:
    spec:
      initContainers:
      - name: wait-for-db
        image: crpi-89ktoa4wv8sjcdow.cn-beijing.personal.cr.aliyuncs.com/namespace-alpha/busybox:1.36
        command: ['sh', '-c', 'until nc -z 39.96.219.254 5432; do echo waiting for db; sleep 2; done;']
      containers:
      - name: api
        imagePullPolicy: Always
        securityContext:
          readOnlyRootFilesystem: false
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        emptyDir: {}
