// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/4/6 20:29:11
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["E:/Git/ai-digital-twin/agenthive-cloud/apps/landing/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Git/ai-digital-twin/agenthive-cloud/apps/landing/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Git/ai-digital-twin/agenthive-cloud/apps/landing/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Git/ai-digital-twin/agenthive-cloud/apps/landing/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Git/ai-digital-twin/agenthive-cloud/apps/landing/plugins/**/*.{js,ts,mjs}","E:/Git/ai-digital-twin/agenthive-cloud/apps/landing/composables/**/*.{js,ts,mjs}","E:/Git/ai-digital-twin/agenthive-cloud/apps/landing/utils/**/*.{js,ts,mjs}","E:/Git/ai-digital-twin/agenthive-cloud/apps/landing/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Git/ai-digital-twin/agenthive-cloud/apps/landing/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","E:/Git/ai-digital-twin/agenthive-cloud/apps/landing/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","E:/Git/ai-digital-twin/agenthive-cloud/apps/landing/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;