server:
  port: 8084

spring:
  application:
    name: order-service
  data:
    redis:
      host: redis
      port: 6379
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
