server:
  port: 8086

spring:
  application:
    name: logistics-service
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
